#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    default_indent = 2
    github_username = 'spankie'
    filemanager = "nerdtree"
    typescript_server_path = "/Users/spankie/.nvm/versions/node/v10.16.0/bin/tsserver"
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "slant"
    statusline_inactive_separator = "slant"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

# vim-go support
[[layers]]
  name = "lang#go"

[[layers]]
  name = "git"

[[layers]]
  name = "github"

[[layers]]
  name = "lang#php"

[[layers]]
  name = "lang#vim"

[[layers]]
  name = "lang#typescript"

# gofmt for go files
# [[layers]]
  # name = "format"

# javascript support
[[layers]]
  name = "lang#javascript"

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

# This is an example for adding custom plugins lilydjwg/colorizer
[[custom_plugins]]
  name = "lilydjwg/colorizer"
  merged = false

# onedark colorscheme
[[custom_plugins]]
	name = "joshdick/onedark.vim"

# surround highlighted text with quotes or brackets
[[custom_plugins]]
	name = "tpope/vim-surround"

[[custom_plugins]]
  name = "ryanoasis/vim-devicons"

# enable multiple cursors
[[custom_plugins]]
	name = "terryma/vim-multiple-cursors"

# [[custom_plugins]]
  # name = "peitalin/vim-jsx-typescript"
#
# [[custom_plugins]]
  # name = "leafgarland/typescript-vim"

[[custom_plugins]]
  name = "wakatime/vim-wakatime"

# prettier support
[[custom_plugins]]
  name = "prettier/vim-prettier"
	do = 'yarn install'
	for = ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue', 'yaml', 'html']
